const DoctorList = [
  {
    name: '이현철',
    specialty: '내과 전문의',
    field: ['내과', '가정의학과'],
    rate: '4.4',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: true,
  },
  {
    name: '양지웅',
    specialty: '안과 전문의',
    field: ['안과'],
    rate: '4.8',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: true,
  },
  {
    name: '김재인',
    specialty: '내과 전문의',
    field: ['내과'],
    rate: '5.0',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: false,
  },
  {
    name: '하철환',
    specialty: '소아과 전문의',
    field: ['소아과', '내과'],
    rate: '4.7',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: true,
  },
  {
    name: '서진형',
    specialty: '가정의학과 전문의',
    field: ['가정의학과'],
    rate: '4.9',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: false,
  },
  {
    name: '송보경',
    specialty: '이비인후과 전문의',
    field: ['이비인후과'],
    rate: '4.5',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: true,
  },
  {
    name: '홍길동',
    specialty: '소아과 전문의',
    field: ['소아과', '내과'],
    rate: '4.7',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: true,
  },
  {
    name: '콩쥐',
    specialty: '가정의학과 전문의',
    field: ['가정의학과'],
    rate: '4.9',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: false,
  },
  {
    name: '팥쥐',
    specialty: '이비인후과 전문의',
    field: ['이비인후과'],
    rate: '4.5',
    img: 'https://i.namu.wiki/i/AzUH8U5TcGdNJDN9Fl5zyEsLdL72N-PBsR0OjvAtmHRAwSDIcDwRAfYS5m_X_i0KFlZdmGNkwb5f8D_eC3vTuQ.webp',
    isFavorite: false,
  },
];
export default DoctorList;
